image: node:latest

stages:
  - deploy


deploy:
  stage: deploy

  script:
    - echo "Deploying"
    - pwd
    - cd react
    - npm install
    - npm run build
    - rm -r /app001/www/pancreatlas/build/*
    - mv ./build/* /app001/www/pancreatlas/build

  environment:
    name: local-dev
    
  tags:
    - dev7-runner

  only:
    - development
