image: node:latest

stages:
  - build

cache:
  paths:
    - react/node_modules/

build:
  stage: build
  script:
    - cd react
    - npm install
    - npm run build
  artifacts:
    paths:
      - react/node_modules/