image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - react/node_modules/

build:
  stage: build
  script:
    - cd react
    - npm install
    - npm run build
  artifacts:
    paths:
      - react/node_modules/

deploy_staging:
  stage: deploy
  script:
    - echo "Deploying to staging"

  environment:
    name: local-dev

  only:
    - development