image: node:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cd react
    - echo -e "REACT_APP_API_URL='https://staging-api.pancreatlas.org/api'\nREACT_APP_API_AUTH='Basic bWVzc21lajpwYW5jcmVhdGxhczIwMTk='\nREACT_APP_VERSION=$npm_package_version\nREACT_APP_IMAGE_URL='https://stagin.pancreatlas.org/images'" > .env.development
    - cp .env.development .env.production
    - npm install
    - npm run build
  artifacts:
    paths:
      - react/build/
      - api/
    expire_in: 1 day

test:
  stage: test
  script:
    - cd react
    - npm install
    - npm install -g standard
    - standard --fix
    - npm run test

deploy:
  stage: deploy
  script:
  
    - echo "Deploying"
    - pwd
    - cd react
    - echo "Installing react app"
    - rm -r /app001/www/pancreatlas/www/*
    - mv ./build/* /app001/www/pancreatlas/www
    - echo "React app installed"
    - echo "Installing api"
    - cd ..
    - rm -r /app001/www/pancreatlas/api/*
    - mv ./api/* /app001/www/pancreatlas/api
    - cd /app001/www/pancreatlas/api
    - virtualenv .
    - source bin/activate
    - pip install -r requirements.txt
    - echo "api installed"
    - echo "Restarting Apache"
    - sudo systemctl restart httpd
    - echo "Apache restarted"



  environment:
    name: local-dev
    
  tags:
    - pancreatlas-staging-runner

  only:
    - /^release\/*/
