image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - react/build/
    - api/

build:
  stage: build
  script:
    - cd react
    - npm install
    - npm run build
  artifacts:
    paths:
      - react/build/
      - api/

test:
  stage: test
  script:
    - cd react
    - npm install
    - npm install -g standard
    - standard --fix
    - npm run test

deploy:
  stage: deploy
  script:
  
    - echo "Deploying"
    - pwd

  environment:
    name: local-dev
    
  tags:
    - dev7-runner

  only:
    - development
