image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - react/node_modules/

build:
  stage: build
  script:
    - cd react
    - npm install
    - npm run build
  artifacts:
    paths:
      - react/node_modules/

deploy:
  stage: deploy
  script:
    - echo "Deploying"
    - pwd
    - cd react
    - npm install && npm audit fix
    - npm run build
    - mv ./build /var/www/html

  environment:
    name: local-dev
    
  tags:
    - pancreatlas

  only:
    - development
