image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - react/build/
    - api/

build:
  stage: build
  script:
    - cd react
    - echo "REACT_APP_API_URL='https://dev7-api-pancreatlas.app.vumc.org/api'\nREACT_APP_API_AUTH=''\nREACT_APP_VERSION=$npm_package_version"
    - npm install
    - npm run build
  artifacts:
    paths:
      - react/build/
      - api/

test:
  stage: test
  script:
    - cd react
    - npm install
    - npm install -g standard
    - standard --fix
    - npm run test

deploy:
  stage: deploy
  script:
  
    - echo "Deploying"
    - pwd
    - cd react
    - echo "Installing react app"
    - rm -r /app001/www/pancreatlas/dev7/www/*
    - mv ./build/* /app001/www/pancreatlas/dev7/www
    - echo "React app installed"
    - echo "Installing api"
    - cd ..
    - rm -r /app001/www/pancreatlas/dev7/api/*
    - mv ./api/* /app001/www/pancreatlas/dev7/api
    - cd /app001/www/pancreatlas/dev7/api
    - virtualenv .
    - source bin/activate
    - pip install -r requirements.txt
    - echo "api installed"
    - echo "Restarting Apache"
    - sudo systemctl restart httpd
    - echo "Apache restarted"



  environment:
    name: local-dev
    
  tags:
    - dev7-runner

  only:
    - development
