image: node:latest

stages:
  - deploy

cache:
  paths:
    - react/node_modules/

build:
  stage: build
  script:
    - cd react
    - npm install
    - npm run build
  artifacts:
    paths:
      - react/node_modules/

deploy:
  stage: deploy
  script:
    - echo "Deploying"
    - pwd
    - cd react
    - npm install
    - npm run build

  environment:
    name: local-dev
    
  tags:
    - pancreatlas

  only:
    - development