image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd react
    - echo -e "REACT_APP_API_URL='https://dev7-api-pancreatlas.app.vumc.org/api'\nREACT_APP_API_AUTH=''\nREACT_APP_VERSION=\$npm_package_version\nREACT_APP_IMAGE_URL='https://dev7-pancreatlas.app.vumc.org/images'\nREACT_APP_FIREBASE_API_KEY='AIzaSyAO1rcbZ9IJwiQ18_M1ygRHt-UMo7ifqcw'\nREACT_APP_FIREBASE_AUTH_DOMAIN='pancreatlas-dev.firebaseapp.com'\nREACT_APP_FIREBASE_DATABASE_URL='https://pancreatlas-dev.firebaseio.com'\nREACT_APP_FIREBASE_PROJECT_ID='pancreatlas-dev'\nREACT_APP_FIREBASE_STORAGE_BUCKET='pancreatlas-dev.appspot.com'\nREACT_APP_FIREBASE_MESSAGING_SENDER_ID='1030715621704'\nREACT_APP_FIREBASE_APP_ID='1:1030715621704:web:040ae2a8c1ad7cbaf0337d'\nREACT_APP_FIREBASE_MEASUREMENT_ID='G-NED9MC8953'" > .env.development
    - cp .env.development .env.production
    - npm install
    - npm run build
  artifacts:
    paths:
      - react/build/
      - api/
      - api2/
    expire_in: 1 day

# test:
#  stage: test
#  script:
#    - cd react
#    - npm install
#    - npm install -g standard
#   #  - standard --fix
#    - npm run test

deploy:
  stage: deploy
  script:
    - echo "Deploying"
    - pwd
    - cd react
    - echo "Installing react app"
    - rm -r /app001/www/pancreatlas/dev7/www/*
    - mv ./build/* /app001/www/pancreatlas/dev7/www
    - echo "React app installed"
    - echo "Installing api"
    - cd ..
    # - rm -r /app001/www/pancreatlas/dev7/api/*
    # - rm -r /app001/www/pancreatlas/dev7/api2/*
    - cp -rf ./api/* /app001/www/pancreatlas/dev7/api
    - cp -rf ./api2/* /app001/www/pancreatlas/dev7/api2
    - cd /app001/www/pancreatlas/dev7/api2
    - python3 -m venv .
    - source bin/activate
    - python3 -m pip install -r requirements.txt
    - sudo systemctl restart httpd


  environment:
    name: local-dev
    
  tags:
    - dev7-runner

  only:
    - development